apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hpe8vqlmo-python
  janus-idp.io/tekton: hpe8vqlmo-python
  backstage.io/kubernetes-id: hpe8vqlmo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpe8vqlmo-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
