apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hpe8vqlmo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hpe8vqlmo-python 
  name: hpe8vqlmo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hpe8vqlmo-python 
